language: python
python:
  - 3.5
services:
  - docker
install:
  - docker build -t mash:2.1 mash/2.1
  - docker build -t mashtree:0.52 mashtree/0.52.0
  - docker build -t spades:3.13.0 spades/3.13.0
  - docker build -t quast:5.0.2 quast/5.0.2
  - docker build -t shovill:1.0.4 shovill/1.0.4
  - docker build -t samtools:1.9 samtools/1.9
script:
  - bash tests/mash-test.sh
  - bash tests/mashtree-test.sh
  - bash tests/spades.sh
  - bash tests/quast.sh
  - bash tests/shovill.sh
  - bash tests/samtools.sh
